# -*- coding: utf-8 -*-
"""ChatBot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tC6PH_tp8PbzOekvgRKcoO4qGDnIOmp_
"""

#pip install chatterbot

from chatterbot import ChatBot 
from chatterbot.trainers import ListTrainer
from tkinter import * 

bot = ChatBot("BOT") 

conversation = [ 
'Hello', 
'My name is bot. I am created by navneet', 
'I am doing great, what about you ?', 
'Oh great to hear that', 
'Sorry to hear that', 
'I live in your computer', 
'I am just a week year old', 
'I speak only in english language', 
'I have no idea how I am created, must be some genius', 
'Thank you' ] 

trainer = ListTrainer(bot)
trainer.train(conversation) 

while True: 
	print("You: ") 
	ques = input() 
	if ques == 'exit': 
		break 
	ans = bot.get_response(ques) 
	print("Bot: ", ans)
 
main = Tk()
main.mainloop()
